<?php layout('layouts.app'); section('content'); ?>
<div class="page-head">
    <div>
        <h1>Staff Payslip</h1>
        <p class="lede"><?= e($payslip['first_name'] . ' ' . $payslip['last_name']) ?> (<?= e($payslip['staff_number']) ?>)</p>
    </div>
    <div class="d-flex gap-2">
        <button class="btn btn-sm btn-outline-secondary" onclick="window.print()"><?= icon('download', 'ico-sm') ?> Print Payslip</button>
        <a class="btn btn-sm btn-light" href="<?= url('/finance/payroll/' . $payslip['payroll_period_id']) ?>">&larr; Back to Period</a>
    </div>
</div>

<div class="card p-4">
    <div class="border-bottom pb-3 mb-3 d-flex justify-content-between align-items-center">
        <div>
            <h4 class="mb-0 fw-bold"><?= e($appName) ?></h4>
            <div class="text-muted-sm">Salary Payslip</div>
        </div>
        <div class="text-end">
            <div class="fw-bold text-primary fs-5"><?= e($payslip['period_name'] ?? ($payslip['month'] . '/' . $payslip['year'])) ?></div>
            <div class="text-muted-sm">Pay Date: <?= date_fmt($payslip['pay_date'] ?? '') ?></div>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-sm-6">
            <h6 class="text-muted">Employee Details:</h6>
            <div class="fw-bold fs-6"><?= e($payslip['first_name'] . ' ' . $payslip['last_name']) ?></div>
            <div>Staff No: <code><?= e($payslip['staff_number']) ?></code></div>
            <div>Designation: <?= e($payslip['designation'] ?? 'Staff') ?></div>
            <div>Email: <?= e($payslip['email']) ?></div>
        </div>
    </div>

    <div class="table-wrap mb-4">
        <table class="table table-bordered">
            <thead class="table-light">
                <tr>
                    <th>Item Description</th>
                    <th class="text-end">Amount (<?= e(currency_code()) ?>)</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Basic Salary</td>
                    <td class="text-end fw-semibold"><?= e(money($payslip['basic_salary'])) ?></td>
                </tr>
                <tr class="table-light fw-bold">
                    <td>Gross Pay</td>
                    <td class="text-end"><?= e(money($payslip['gross_pay'] ?? $payslip['basic_salary'])) ?></td>
                </tr>
                <tr class="table-success fw-bold fs-6">
                    <td>Net Pay</td>
                    <td class="text-end text-success"><?= e(money($payslip['net_pay'] ?? $payslip['basic_salary'])) ?></td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="text-center text-muted-sm mt-3">
        Confidential Employee Salary Statement. Generated by <?= e($appName) ?>.
    </div>
</div>
<?php endsection(); ?>
