-- University System Admin Seed SQL
-- Import this file into phpMyAdmin after importing schema.sql

-- 1. Insert Core Roles
INSERT INTO `roles` (`id`, `name`, `slug`, `description`, `level`, `is_system`) VALUES
(1, 'Super Administrator', 'super-admin', 'Unrestricted access to every part of the system.', 1, 1),
(2, 'Vice Chancellor', 'vice-chancellor', 'Executive oversight with read access across the institution.', 2, 1),
(3, 'Registrar', 'registrar', 'Owns admissions, student records and examinations.', 3, 1),
(4, 'Dean', 'dean', 'Faculty-level academic oversight.', 4, 1),
(5, 'Head of Department', 'hod', 'Departmental academic management.', 5, 1),
(6, 'Lecturer', 'lecturer', 'Teaches classes, records attendance and enters marks.', 6, 1),
(7, 'Finance Officer', 'finance-officer', 'Fees, invoicing, receipting and payroll.', 5, 1),
(8, 'Librarian', 'librarian', 'Manages the library catalogue and circulation.', 6, 1),
(9, 'Hostel Warden', 'warden', 'Manages accommodation and room allocation.', 6, 1),
(10, 'HR Officer', 'hr-officer', 'Staff records, leave and payroll input.', 5, 1),
(11, 'Admissions Officer', 'admissions-officer', 'Processes applications and enrolment.', 5, 1),
(12, 'Medical Officer', 'medical-officer', 'Maintains student health records.', 6, 1),
(13, 'Support Desk', 'support-desk', 'Handles the helpdesk queue.', 7, 1),
(14, 'Student', 'student', 'Access to the student self-service portal.', 9, 1),
(15, 'Parent / Guardian', 'guardian', 'Read-only view of a linked student.', 9, 1)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `description` = VALUES(`description`), `level` = VALUES(`level`);

-- 2. Insert Core Permissions
INSERT INTO `permissions` (`name`, `slug`, `module`, `description`) VALUES
('View dashboard', 'dashboard.view', 'dashboard', 'View dashboard'),
('View user accounts', 'users.view', 'users', 'View user accounts'),
('Create users', 'users.create', 'users', 'Create users'),
('Edit users', 'users.edit', 'users', 'Edit users'),
('Delete users', 'users.delete', 'users', 'Delete users'),
('Reset passwords', 'users.reset', 'users', 'Reset passwords'),
('View roles', 'roles.view', 'roles', 'View roles'),
('Create roles', 'roles.create', 'roles', 'Create roles'),
('Edit roles', 'roles.edit', 'roles', 'Edit roles'),
('Delete roles', 'roles.delete', 'roles', 'Delete roles'),
('Assign permissions', 'roles.assign', 'roles', 'Assign permissions'),
('Manage system settings', 'settings.manage', 'settings', 'Manage system settings'),
('View the audit trail', 'audit.view', 'audit', 'View the audit trail'),
('View academic structure', 'academics.view', 'academics', 'View academic structure'),
('Create academic records', 'academics.create', 'academics', 'Create academic records'),
('Edit academic records', 'academics.edit', 'academics', 'Edit academic records'),
('Delete academic records', 'academics.delete', 'academics', 'Delete academic records'),
('Manage calendar and curriculum', 'academics.manage', 'academics', 'Manage calendar and curriculum'),
('View class offerings', 'offerings.view', 'offerings', 'View class offerings'),
('Create class offerings', 'offerings.create', 'offerings', 'Create class offerings'),
('Edit class offerings', 'offerings.edit', 'offerings', 'Edit class offerings'),
('Delete class offerings', 'offerings.delete', 'offerings', 'Delete class offerings'),
('View course registrations', 'registrations.view', 'registrations', 'View course registrations'),
('Register students', 'registrations.create', 'registrations', 'Register students'),
('Edit registrations', 'registrations.edit', 'registrations', 'Edit registrations'),
('Drop registrations', 'registrations.delete', 'registrations', 'Drop registrations'),
('Approve registrations', 'registrations.approve', 'registrations', 'Approve registrations'),
('View applications', 'admissions.view', 'admissions', 'View applications'),
('Capture applications', 'admissions.create', 'admissions', 'Capture applications'),
('Edit applications', 'admissions.edit', 'admissions', 'Edit applications'),
('Delete applications', 'admissions.delete', 'admissions', 'Delete applications'),
('Manage intakes', 'admissions.manage', 'admissions', 'Manage intakes'),
('Review applications', 'admissions.review', 'admissions', 'Review applications'),
('Enrol applicants', 'admissions.enrol', 'admissions', 'Enrol applicants'),
('View students', 'students.view', 'students', 'View students'),
('Admit students', 'students.create', 'students', 'Admit students'),
('Edit student records', 'students.edit', 'students', 'Edit student records'),
('Remove students', 'students.delete', 'students', 'Remove students'),
('Change student status', 'students.status', 'students', 'Change student status'),
('View staff', 'staff.view', 'staff', 'View staff'),
('Add staff', 'staff.create', 'staff', 'Add staff'),
('Edit staff', 'staff.edit', 'staff', 'Edit staff'),
('Remove staff', 'staff.delete', 'staff', 'Remove staff'),
('Access the lecturer workspace', 'teaching.access', 'teaching', 'Access the lecturer workspace'),
('Access the student portal', 'portal.access', 'portal', 'Access the student portal'),
('View attendance', 'attendance.view', 'attendance', 'View attendance'),
('Create attendance sessions', 'attendance.create', 'attendance', 'Create attendance sessions'),
('Mark attendance', 'attendance.edit', 'attendance', 'Mark attendance'),
('Delete attendance sessions', 'attendance.delete', 'attendance', 'Delete attendance sessions'),
('View the timetable', 'timetable.view', 'timetable', 'View the timetable'),
('Create timetable slots', 'timetable.create', 'timetable', 'Create timetable slots'),
('Edit timetable slots', 'timetable.edit', 'timetable', 'Edit timetable slots'),
('Delete timetable slots', 'timetable.delete', 'timetable', 'Delete timetable slots'),
('View examinations', 'exams.view', 'exams', 'View examinations'),
('Schedule examinations', 'exams.create', 'exams', 'Schedule examinations'),
('Edit examinations', 'exams.edit', 'exams', 'Edit examinations'),
('Delete examinations', 'exams.delete', 'exams', 'Delete examinations'),
('View results', 'results.view', 'results', 'View results'),
('Enter marks', 'results.create', 'results', 'Enter marks'),
('Amend marks', 'results.edit', 'results', 'Amend marks'),
('Delete results', 'results.delete', 'results', 'Delete results'),
('Manage grading', 'results.manage', 'results', 'Manage grading'),
('Publish results', 'results.publish', 'results', 'Publish results'),
('View finance records', 'finance.view', 'finance', 'View finance records'),
('Create invoices and payments', 'finance.create', 'finance', 'Create invoices and payments'),
('Edit finance records', 'finance.edit', 'finance', 'Edit finance records'),
('Delete finance records', 'finance.delete', 'finance', 'Delete finance records'),
('Manage fee structures', 'finance.manage', 'finance', 'Manage fee structures'),
('Reverse payments', 'finance.reverse', 'finance', 'Reverse payments'),
('View payroll', 'payroll.view', 'payroll', 'View payroll'),
('Run payroll', 'payroll.create', 'payroll', 'Run payroll'),
('Edit payslips', 'payroll.edit', 'payroll', 'Edit payslips'),
('Delete payroll periods', 'payroll.delete', 'payroll', 'Delete payroll periods'),
('View the library', 'library.view', 'library', 'View the library'),
('Add titles', 'library.create', 'library', 'Add titles'),
('Edit titles', 'library.edit', 'library', 'Edit titles'),
('Remove titles', 'library.delete', 'library', 'Remove titles'),
('Issue and receive books', 'library.issue', 'library', 'Issue and receive books'),
('View accommodation', 'hostel.view', 'hostel', 'View accommodation'),
('Create hostels and rooms', 'hostel.create', 'hostel', 'Create hostels and rooms'),
('Edit accommodation', 'hostel.edit', 'hostel', 'Edit accommodation'),
('Delete accommodation', 'hostel.delete', 'hostel', 'Delete accommodation'),
('Allocate rooms', 'hostel.allocate', 'hostel', 'Allocate rooms'),
('View clearance', 'clearance.view', 'clearance', 'View clearance'),
('Sign off clearance', 'clearance.edit', 'clearance', 'Sign off clearance'),
('View health records', 'medical.view', 'medical', 'View health records'),
('Add health records', 'medical.create', 'medical', 'Add health records'),
('Edit health records', 'medical.edit', 'medical', 'Edit health records'),
('Delete health records', 'medical.delete', 'medical', 'Delete health records'),
('View disciplinary cases', 'discipline.view', 'discipline', 'View disciplinary cases'),
('Open cases', 'discipline.create', 'discipline', 'Open cases'),
('Update cases', 'discipline.edit', 'discipline', 'Update cases'),
('Delete cases', 'discipline.delete', 'discipline', 'Delete cases'),
('View support tickets', 'tickets.view', 'tickets', 'View support tickets'),
('Raise tickets', 'tickets.create', 'tickets', 'Raise tickets'),
('Respond to tickets', 'tickets.edit', 'tickets', 'Respond to tickets'),
('Delete tickets', 'tickets.delete', 'tickets', 'Delete tickets'),
('View HR records', 'hr.view', 'hr', 'View HR records'),
('Create HR records', 'hr.create', 'hr', 'Create HR records'),
('Edit HR records', 'hr.edit', 'hr', 'Edit HR records'),
('Delete HR records', 'hr.delete', 'hr', 'Delete HR records'),
('Approve leave', 'hr.manage', 'hr', 'Approve leave'),
('View documents', 'documents.view', 'documents', 'View documents'),
('Upload documents', 'documents.create', 'documents', 'Upload documents'),
('Edit documents', 'documents.edit', 'documents', 'Edit documents'),
('Delete documents', 'documents.delete', 'documents', 'Delete documents'),
('View announcements', 'announcements.view', 'announcements', 'View announcements'),
('Publish announcements', 'announcements.create', 'announcements', 'Publish announcements'),
('Edit announcements', 'announcements.edit', 'announcements', 'Edit announcements'),
('Delete announcements', 'announcements.delete', 'announcements', 'Delete announcements'),
('View events', 'events.view', 'events', 'View events'),
('Create events', 'events.create', 'events', 'Create events'),
('Edit events', 'events.edit', 'events', 'Edit events'),
('Delete events', 'events.delete', 'events', 'Delete events'),
('View reports', 'reports.view', 'reports', 'View reports'),
('Export reports', 'reports.export', 'reports', 'Export reports')
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `description` = VALUES(`description`);

-- 3. Grant All Permissions to Super Administrator Role (Role ID = 1)
INSERT IGNORE INTO `role_permissions` (`role_id`, `permission_id`)
SELECT 1, `id` FROM `permissions`;

-- 4. Create Super Administrator Account
-- Username: admin
-- Password: Admin2026!
INSERT INTO `users` (
  `id`, `uuid`, `username`, `email`, `password_hash`, `title`, `first_name`, `last_name`,
  `gender`, `phone`, `user_type`, `status`, `email_verified_at`
) VALUES (
  1,
  'a0000000-0000-4000-8000-000000000001',
  'admin',
  'admin@bestbrain.edu.lr',
  '$2y$10$Sjt761clz/pXBqVUc21l.OIcOxoCq1agS84JzTZsrEsUWqYcr7DAO',
  'Mr',
  'System',
  'Administrator',
  'male',
  '+231770000000',
  'admin',
  'active',
  NOW()
)
ON DUPLICATE KEY UPDATE
  `password_hash` = VALUES(`password_hash`),
  `status` = 'active';

-- 5. Link Admin User to Super Administrator Role
INSERT IGNORE INTO `user_roles` (`user_id`, `role_id`) VALUES (1, 1);

-- 6. Insert Default System Settings
INSERT INTO `settings` (`setting_key`, `setting_value`, `setting_group`, `data_type`, `label`) VALUES
('institution_name', 'Best Brain University', 'general', 'string', 'Institution name'),
('institution_short_name', 'BBU', 'general', 'string', 'Short name / abbreviation'),
('institution_motto', 'Excellence in Education & Innovation', 'general', 'string', 'Motto'),
('institution_email', 'info@bestbrain.edu.lr', 'general', 'string', 'Official email'),
('institution_phone', '+231 77 000 000', 'general', 'string', 'Telephone'),
('institution_address', 'Monrovia, Liberia', 'general', 'text', 'Postal address'),
('institution_country', 'Liberia', 'general', 'string', 'Country'),
('institution_website', 'https://www.bestbrain.edu.lr', 'general', 'string', 'Website'),
('institution_logo', '', 'general', 'file', 'Institution Logo'),
('support_email', 'ict@bestbrain.edu.lr', 'general', 'string', 'ICT helpdesk email'),
('academic_year_label', '2025/2026', 'academic', 'string', 'Current academic year label'),
('min_credits_per_semester', '12', 'academic', 'integer', 'Minimum credit hours per semester'),
('max_credits_per_semester', '21', 'academic', 'integer', 'Maximum credit hours per semester'),
('pass_mark', '40', 'academic', 'integer', 'Overall pass mark (percent)'),
('coursework_weight', '30', 'academic', 'integer', 'Default coursework weighting (percent)'),
('exam_weight', '70', 'academic', 'integer', 'Default examination weighting (percent)'),
('attendance_threshold', '75', 'academic', 'integer', 'Minimum attendance to sit exams (percent)'),
('require_registration_approval', '1', 'academic', 'boolean', 'Course registrations need approval'),
('fee_threshold_percent', '60', 'finance', 'integer', 'Minimum fee paid (percent) before registration'),
('currency_code', 'USD', 'finance', 'string', 'Currency code'),
('currency_symbol', '$', 'finance', 'string', 'Currency symbol'),
('invoice_due_days', '30', 'finance', 'integer', 'Days until an invoice falls due'),
('late_payment_penalty', '0', 'finance', 'decimal', 'Late payment penalty (percent)'),
('library_loan_days', '14', 'library', 'integer', 'Standard loan period (days)'),
('library_borrow_limit', '3', 'library', 'integer', 'Titles a member may hold at once'),
('library_fine_per_day', '1.00', 'library', 'decimal', 'Overdue fine per day ($)'),
('library_max_renewals', '2', 'library', 'integer', 'Maximum renewals per loan'),
('hostel_application_open', '1', 'hostel', 'boolean', 'Accommodation applications are open')
ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`), `label` = VALUES(`label`);

